#include<stdio.h>
int main()
{
    int t;
    scanf("%d",&t);
    while(t--)
    {

        int x,i;
        scanf("%d",&x);
        int n=0,m;
        m=x;
        while(m!=0)
        {
            m=m/10;
            n++;
        }
        i=x%10;


        if(i==1&&n==1)
        {
            printf("%d\n",n);
        }
        if(i==1&&n==2)
        {
            printf("%d\n",n+1);
        }
        if(i==1&&n==3)
        {
            printf("%d\n",n+1+2);
        }
        if(i==1&&n==4)
        {
            printf("%d\n",n+1+2+3);
        }
        if(i==2&&n==1)
        {
            printf("%d\n",10+n);
        }
        if(i==2&&n==2)
        {
            printf("%d\n",10+n+1);
        }
        if(i==2&&n==3)
        {
            printf("%d\n",10+n+1+2);
        }
        if(i==2&&n==4)
        {
            printf("%d\n",10+n+1+2+3);
        }
        if(i==3&&n==1)
        {
            printf("%d\n",20+n);
        }
        if(i==3&&n==2)
        {
            printf("%d\n",20+n+1);
        }
        if(i==3&&n==3)
        {
            printf("%d\n",20+n+1+2);
        }
        if(i==3&&n==4)
        {
            printf("%d\n",20+n+1+2+3);
        }
        if(i==4&&n==1)
        {
            printf("%d\n",30+n);
        }
        if(i==4&&n==2)
        {
            printf("%d\n",30+n+1);
        }
        if(i==4&&n==3)
        {
            printf("%d\n",30+n+1+2);
        }
        if(i==4&&n==4)
        {
            printf("%d\n",30+n+1+2+3);
        }
        if(i==5&&n==1)
        {
            printf("%d\n",40+n);
        }
        if(i==5&&n==2)
        {
            printf("%d\n",40+n+1);
        }
        if(i==5&&n==3)
        {
            printf("%d\n",40+n+1+2);
        }
        if(i==5&&n==4)
        {
            printf("%d\n",40+n+1+2+3);
        }
        if(i==6&&n==1)
        {
            printf("%d\n",50+n);
        }
        if(i==6&&n==2)
        {
            printf("%d\n",50+n+1);
        }
        if(i==6&&n==3)
        {
            printf("%d\n",50+n+1+2);
        }
        if(i==6&&n==4)
        {
            printf("%d\n",50+n+1+2+3);
        }
        if(i==7&&n==1)
        {
            printf("%d\n",60+n);
        }
        if(i==7&&n==2)
        {
            printf("%d\n",60+n+1);
        }
        if(i==7&&n==3)
        {
            printf("%d\n",60+n+1+2);
        }
        if(i==7&&n==4)
        {
            printf("%d\n",60+n+1+2+3);
        }
        if(i==8&&n==1)
        {
            printf("%d\n",70+n);
        }
        if(i==8&&n==2)
        {
            printf("%d\n",70+n+1);
        }
        if(i==8&&n==3)
        {
            printf("%d\n",70+n+1+2);
        }
        if(i==8&&n==4)
        {
            printf("%d\n",70+n+1+2+3);
        }
        if(i==9&&n==1)
        {
            printf("%d\n",80+n);
        }
        if(i==9&&n==2)
        {
            printf("%d\n",80+n+1);
        }
        if(i==9&&n==3)
        {
            printf("%d\n",80+n+1+2);
        }
        if(i==9&&n==4)
        {
            printf("%d\n",80+n+1+2+3);
        }


    }
}
